# Introduction to PyTorch

## PyTorch Tensors

In [1]:
import torch

In [7]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)  # query datatype

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [5]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [10]:
# Init learning weights randomly with spec PRNG seed for reproducibility

torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print("A random tensor:")
print(r1)

r2 = torch.rand(2, 2)
print("\nA different random tensor:")
print(r2)  # new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print("Should match r1:")
print(r3)  # repeats r1 values becaused re-seeded

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [11]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2
print(twos)

threes = ones + twos  # addition allowed because shapes are similar
print(threes)         # tensors added element-wise
print(threes.shape)   # has same dims as input tensors

r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)
r3 = r1 + r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [14]:
r = (torch.rand(2, 2) - 0.5) * 2  # values in [-1, 1]
print("A random matrix, r:")
print(r)

# Common math ops supported:
print("\nAbsolute value of r:")
print(torch.abs(r))

# ...as are trig funcs:
print("\nInverse sine of r:")
print(torch.abs(r))

# ...and lin-alg ops
print("\nDeterminant of r:")
print(torch.det(r))
print("\nSingular value decomposition of r:")
print(torch.svd(r))

# ...stat and aggregate ops:
print("\nMean and standard deviation of r:")
print(torch.std_mean(r))
print("\nMaximum value of r:")
print(torch.max(r))

A random matrix, r:
tensor([[ 0.0124,  0.6939],
        [-0.4823, -0.4587]])

Absolute value of r:
tensor([[0.0124, 0.6939],
        [0.4823, 0.4587]])

Inverse sine of r:
tensor([[0.0124, 0.6939],
        [0.4823, 0.4587]])

Determinant of r:
tensor(0.3290)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[ 0.7278, -0.6858],
        [-0.6858, -0.7278]]),
S=tensor([0.8872, 0.3708]),
V=tensor([[ 0.3830,  0.9237],
        [ 0.9237, -0.3830]]))

Mean and standard deviation of r:
(tensor(0.5510), tensor(-0.0587))

Maximum value of r:
tensor(0.6939)


## PyTorch Models

In [ ]:
import torch.nn as nn            # parent obj for PyTorch models
import torch.nn.functional as F  # for activation func

LeNet-5 was one of the earliest convolutional neural nets, and one of the drivers of the explosion in Deep Learning. It was built to read small images of handwritten numbers (the MNIST dataset), and correctly classify which digit was represented in the image.

<img src="https://pytorch.org/tutorials/_images/mnist.png" height="200">

Abridged version of how it works:
* Layer C1: convolutional layer
    * Scans input image for features learned during training
    * Outputs map of where it saw each of its learned features in the image
* Layer S2: downsamples this “activation map”
* Layer C3: another convolutional layer
    * Scans C1’s activation map for feature combinations
    * Outputs activation map describing spatial locations of these feature combinations
* Layer S4: downsamples this activation map
* Fully-connected layers at the end: F5, F6, OUTPUT
    * Classifier that takes final activation map and classifies it into one of ten bins representing the 10 digits

In [ ]:
class LeNet(nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)

        self.fc1 = nn.Linear(16)